#!/usr/bin/env node

const argv = require('minimist')(process.argv.slice(2))
const {create, cli} = require('./dist/index')

if (argv.help || process.argv.indexOf('help') >= 0) {
  cli.print('WHAT Up.')
} else {
  create(argv, {argv})
}

